bookers/config/routes.rb
Rails.application.routes.draw do
  # get 'books/new'
  # get 'books/index'
  # get 'books/show'
  # get 'books/edit'
  root 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers/app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      flash.now[:alert]
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
     @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "Book was successfully updated."
    else
      flash.now[:alert]
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/helpers/homes_helper.rb
module HomesHelper
end

bookers/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>

<p>Title</p>
<%= f.text_field :title %>

<p>body</p>
<%= f.text_area :body %>
<%= f.submit 'Update Book' %>
<% end %>

<%= link_to 'Show', book_path(@book.id) %> | <%= link_to 'Back', books_path %>

bookers/app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <tr>
<th><p>title</p></th>
<th><p>body</p></th>
<th></th>
<th></th>
<th></th>

</tr>
<% @books.each do |book| %>
<tr>
  <td><span><%= book.title %></span></td>
  <td><span><%= book.body %></span></td>
  <td><%= link_to "Show", book_path(book.id) %></td>
  <td><%= link_to "Edit", edit_book_path(book.id) %></td>
  <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
</tr>
<% end %>
</table>
<h1>New book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: Book.new do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>

<% end %>

bookers/app/views/books/show.html.erb
<h2>title :<%= @book.title %> </h2>

<p>body : <%= @book.body %></p>

<%= link_to 'edit', edit_book_path(@book.id) %> | <%= link_to 'back', books_path %>

bookers/app/views/homes/top.html.erb
<h1>ようこそBookersへ！</h1>

 <p>Bookersでは、さまざまな書籍に関するあなたの意見や</p>

 <P>印象を共有し交換することができます</P>

 <p><%= link_to "start", books_path %></p>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>">Book was successfully created.</div>
      <% end %>
    <%= yield %>
  </body>
</html>